baseURL: 'https://kameniksolutions.com'
languageCode: 'en-us'
title: 'Kamenik Solutions'

timeZone: America/New_York

# Setup the Threme
module:
  imports:
    - path: github.com/imfing/hextra

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block: [['\[', '\]'], ['$$', '$$']]
          inline: [['\(', '\)']]
        enable: true

menu:
  main:
    - name: Radar
      pageRef: /radar
      weight: 1
    - name: Resources
      pageRef: /resources
      weight: 2
    - name: Blog
      pageRef: /blog
      weight: 3
    - name: Search
      weight: 4
      params:
        type: search
    # - name: About
    #   pageRef: /about
    #   weight: 5
    - name: RSS
      weight: 6
      url: "/index.xml"
      params:
        icon: rss

params:
  navbar:
    displayTitle: true
    displayLogo: true

    logo:
      path: images/icon_64.png
      # link: /
      width: 64
      height: 64

  footer:
    displayCopyright: true
    displayPoweredBy: true

  editURL:
    enable: false

  rss:
    sections:
      - radar
      - blog

  displayUpdatedDate: false

  blog:
    list:
      displayTags: false

outputs:
  section:
    - html
    - json

related:
  includeNewer: false
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: true
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 0
    name: date
    pattern: ""
    toLower: false
    type: basic
    weight: 10
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ""
    toLower: true
    type: basic
    weight: 80
  threshold: 80
  toLower: true
